server:
  port: 8004
spring:
  application:
    name: spring-kafka-basic-integration
  kafka:
    bootstrap-servers:
      - "172.21.0.3:9092"
  datasource:
    username: dear
    password: comrade
    # url: jdbc:postgresql://172.19.0.2:5432/dear_comrade
    url: jdbc:postgresql://localhost:5432/dear_comrade
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
        show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html