spring:
  cloud:
    function:
      definition: nameProducer;wordCountProcess;wordCountHandler
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          nameProducer-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
        streams:
          bindings:
            wordCountProcess-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.pool.config.serdes.WordSerDe
            wordCountHandler-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            wordCountProcess-out-0:
#              producer:
#                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
          binder:
            configuration:
              commit.interval.ms: 2000
      bindings:
        nameProducer-out-0:
          destination: news-1-topic
        wordCountProcess-in-0:
          destination: news-1-topic
        wordCountProcess-out-0:
          destination: news-1-count-topic
        wordCountHandler-in-0:
          destination: news-1-count-topic
        wordCountHandler-out-0:
          destination: news-2-count-topic

enable:
  comrade-kafka: false
  basic-kafka: false
  modified-kafka: false

